
.release image:
  image: $CI_REGISTRY/$SG_CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: image build
  timeout: 1 hour
  script:
    - |
      [ "$DEBUG" != true ] || set -x
      export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}$IMAGE_SUFFIX"
      export IMAGE_NAME="$CI_REGISTRY/$SG_CI_PROJECT_PATH/$IMAGE_BASE_NAME:$IMAGE_TAG"
      mkdir -p $HOME/.docker                                                                                                                                                                               
      cat "$DOCKER_AUTH_CONFIG" > "$HOME/.docker/config.json"                                                                                                                                              
      echo | docker login "$CI_REGISTRY" || \
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      flock "$LOCK_FILE" \
        sh stackgres-k8s/ci/build/build-gitlab.sh build \
          "$IMAGE_MODULE_NAME"
      HASH_IMAGE_NAME="$(sh stackgres-k8s/ci/build/build-functions.sh image_name "$IMAGE_MODULE_NAME")"
      docker pull "$HASH_IMAGE_NAME"
      docker tag "$HASH_IMAGE_NAME" "$IMAGE_NAME"
      docker push "$IMAGE_NAME"
  retry: 2

.release image multi archs:
  image: docker:24.0.7
  stage: image build multi archs
  timeout: 1 hour
  script:
    - |
      [ "$DEBUG" != true ] || set -x
      export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}$IMAGE_SUFFIX"
      export IMAGE_NAME="$IMAGE_BASE_NAME:$IMAGE_TAG"
      export TARGET_IMAGE_NAME="$CI_REGISTRY/$SG_CI_PROJECT_PATH/$IMAGE_NAME"
      mkdir -p $HOME/.docker                                                                                                                                                                               
      cat "$DOCKER_AUTH_CONFIG" > "$HOME/.docker/config.json"                                                                                                                                              
      echo | docker login "$CI_REGISTRY" || \
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      cd stackgres-k8s/src
      ARCH_LIST="amd64 $(
        if [ "$DO_ARM" = true ] \
          || { [ "$SKIP_ARM" != true ] && [ -n "$CI_COMMIT_TAG" ]; }
        then
          echo arm64
        fi
        )"
      if docker manifest inspect "$TARGET_IMAGE_NAME" >/dev/null 2>&1
      then
        docker pull registry.gitlab.com/ongresinc/stackgres/placeholder
        docker tag registry.gitlab.com/ongresinc/stackgres/placeholder "$TARGET_IMAGE_NAME"
        docker push "$TARGET_IMAGE_NAME"
      fi
      docker manifest rm "$TARGET_IMAGE_NAME" 2>/dev/null || true
      docker manifest create "$TARGET_IMAGE_NAME" $(
        for ARCH in $ARCH_LIST
        do
          echo "$TARGET_IMAGE_NAME-$ARCH "
        done)
      docker manifest push "$TARGET_IMAGE_NAME"
  retry: 2

.release jvm image amd64:
  extends: .release image
  dependencies:
    - build amd64
  tags:
    - stackgres-runner-v2
    - linux-amd64
  variables:
    IMAGE_SUFFIX: '-release-jvm-amd64'
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_RELEASE_IMAGE

.release native image amd64:
  extends: .release image
  dependencies:
    - build amd64
  tags:
    - stackgres-runner-v2
    - linux-amd64
  variables:
    IMAGE_SUFFIX: '-release-amd64'
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY && $DO_NATIVE
      - $DO_RELEASE_IMAGE && $DO_NATIVE

release operator jvm image amd64:
  extends: .release jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/operator
    LOCK_FILE: stackgres-operator-release-jvm-release-image
    IMAGE_MODULE_NAME: operator-jvm-release-image

release restapi jvm image amd64:
  extends: .release jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/restapi
    LOCK_FILE: stackgres-restapi-release-jvm-release-image
    IMAGE_MODULE_NAME: restapi-jvm-release-image

release jobs jvm image amd64:
  extends: .release jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/jobs
    LOCK_FILE: stackgres-jobs-release-jvm-release-image
    IMAGE_MODULE_NAME: jobs-jvm-release-image

release cluster-controller jvm image amd64:
  extends: .release jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller
    LOCK_FILE: stackgres-cluster-controller-release-jvm-release-image
    IMAGE_MODULE_NAME: cluster-controller-jvm-release-image

release stream jvm image amd64:
  extends: .release jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/stream
    LOCK_FILE: stackgres-stream-release-jvm-release-image
    IMAGE_MODULE_NAME: stream-jvm-release-image

release operator native image amd64:
  extends: .release native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/operator
    LOCK_FILE: stackgres-operator-release-native-release-image
    IMAGE_MODULE_NAME: operator-native-release-image

release restapi native image amd64:
  extends: .release native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/restapi
    LOCK_FILE: stackgres-restapi-release-native-release-image
    IMAGE_MODULE_NAME: restapi-native-release-image

release jobs native image amd64:
  extends: .release native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/jobs
    LOCK_FILE: stackgres-jobs-release-native-release-image
    IMAGE_MODULE_NAME: jobs-native-release-image

release cluster-controller native image amd64:
  extends: .release native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller
    LOCK_FILE: stackgres-cluster-controller-release-native-release-image
    IMAGE_MODULE_NAME: cluster-controller-native-release-image

.release stream native image amd64:
  extends: .release native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/stream
    LOCK_FILE: stackgres-stream-release-native-release-image
    IMAGE_MODULE_NAME: stream-native-release-image

release admin-ui image amd64:
  extends: .release image
  dependencies:
    - build amd64
  tags:
    - stackgres-runner-v2
    - linux-amd64
  variables:
    IMAGE_SUFFIX: '-release-amd64'
    IMAGE_BASE_NAME: stackgres/admin-ui
    LOCK_FILE: stackgres-adminui-release-release-image
    IMAGE_MODULE_NAME: admin-ui-release-image
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_RELEASE_IMAGE

.release jvm image arm64:
  extends: .release image
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - linux-arm64
  variables:
    IMAGE_SUFFIX: '-release-jvm-arm64'
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY && $DO_ARM
      - $DO_RELEASE_IMAGE && $DO_ARM

.release native image arm64:
  extends: .release image
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - linux-arm64
  variables:
    IMAGE_SUFFIX: '-release-arm64'
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY && $DO_NATIVE && $DO_ARM
      - $DO_RELEASE_IMAGE && $DO_NATIVE && $DO_ARM

release operator jvm image arm64:
  extends: .release jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/operator
    LOCK_FILE: stackgres-operator-release-jvm-release-image
    IMAGE_MODULE_NAME: operator-jvm-release-image

release restapi jvm image arm64:
  extends: .release jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/restapi
    LOCK_FILE: stackgres-restapi-release-jvm-release-image
    IMAGE_MODULE_NAME: restapi-jvm-release-image

release jobs jvm image arm64:
  extends: .release jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/jobs
    LOCK_FILE: stackgres-jobs-release-jvm-release-image
    IMAGE_MODULE_NAME: jobs-jvm-release-image

release cluster-controller jvm image arm64:
  extends: .release jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller
    LOCK_FILE: stackgres-cluster-controller-release-jvm-release-image
    IMAGE_MODULE_NAME: cluster-controller-jvm-release-image

release stream jvm image arm64:
  extends: .release jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/stream
    LOCK_FILE: stackgres-stream-release-jvm-release-image
    IMAGE_MODULE_NAME: stream-jvm-release-image

release operator native image arm64:
  extends: .release native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/operator
    LOCK_FILE: stackgres-operator-release-native-release-image
    IMAGE_MODULE_NAME: operator-native-release-image

release restapi native image arm64:
  extends: .release native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/restapi
    LOCK_FILE: stackgres-restapi-release-native-release-image
    IMAGE_MODULE_NAME: restapi-native-release-image

release jobs native image arm64:
  extends: .release native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/jobs
    LOCK_FILE: stackgres-jobs-release-native-release-image
    IMAGE_MODULE_NAME: jobs-native-release-image

release cluster-controller native image arm64:
  extends: .release native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller
    LOCK_FILE: stackgres-cluster-controller-release-native-release-image
    IMAGE_MODULE_NAME: cluster-controller-native-release-image

.release stream native image arm64:
  extends: .release native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/stream
    LOCK_FILE: stackgres-stream-release-native-release-image
    IMAGE_MODULE_NAME: stream-native-release-image

release admin-ui image arm64:
  extends: .release image
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - linux-arm64
  variables:
    IMAGE_SUFFIX: '-release-arm64'
    IMAGE_BASE_NAME: stackgres/admin-ui
    LOCK_FILE: stackgres-adminui-release-release-image
    IMAGE_MODULE_NAME: admin-ui-release-image
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY && $DO_ARM
      - $DO_RELEASE_IMAGE && $DO_ARM

.release jvm image multi archs:
  extends: .release image multi archs
  tags:
    - stackgres-runner-v2
  variables:
    IMAGE_SUFFIX: '-release-jvm'
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_RELEASE_IMAGE

.release native image multi archs:
  extends: .release image multi archs
  tags:
    - stackgres-runner-v2
  variables:
    IMAGE_SUFFIX: '-release'
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY && $DO_NATIVE
      - $DO_RELEASE_IMAGE && $DO_NATIVE

release operator jvm image multi archs:
  extends: .release jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/operator

release restapi jvm image multi archs:
  extends: .release jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/restapi

release jobs jvm image multi archs:
  extends: .release jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/jobs

release cluster-controller jvm image multi archs:
  extends: .release jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller

release stream jvm image multi archs:
  extends: .release jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/stream

release operator native image multi archs:
  extends: .release native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/operator

release restapi native image multi archs:
  extends: .release native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/restapi

release jobs native image multi archs:
  extends: .release native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/jobs

release cluster-controller native image multi archs:
  extends: .release native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller

.release stream native image multi archs:
  extends: .release native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/stream

release admin-ui image multi archs:
  extends: .release image multi archs
  tags:
    - stackgres-runner-v2
  variables:
    IMAGE_SUFFIX: '-release'
    IMAGE_BASE_NAME: stackgres/admin-ui
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_RELEASE_IMAGE

.release operator bundle image amd64:
  extends: .release image
  dependencies:
    - build amd64
  tags:
    - stackgres-runner-v2
    - linux-amd64
  variables:
    IMAGE_SUFFIX: '-release-amd64'
    IMAGE_BASE_NAME: stackgres/operator-bundle
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_RELEASE_IMAGE

.release operator bundle image arm64:
  extends: .release image
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - linux-arm64
  variables:
    IMAGE_SUFFIX: '-release-arm64'
    IMAGE_BASE_NAME: stackgres/operator-bundle
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY && $DO_ARM
      - $DO_RELEASE_IMAGE && $DO_ARM

release operator bundle image amd64:
  extends: .release operator bundle image amd64
  variables:
    LOCK_FILE: stackgres-operator-release-bundle-build-image
    IMAGE_MODULE_NAME: operator-release-bundle-image

release operator bundle image arm64:
  extends: .release operator bundle image arm64
  variables:
    LOCK_FILE: stackgres-operator-release-bundle-build-image
    IMAGE_MODULE_NAME: operator-release-bundle-image

release operator openshift bundle image amd64:
  extends: .release operator bundle image amd64
  variables:
    IMAGE_SUFFIX: '-release-openshift-amd64'
    LOCK_FILE: stackgres-operator-release-openshift-bundle-build-image
    IMAGE_MODULE_NAME: operator-release-openshift-bundle-image

release operator openshift bundle image arm64:
  extends: .release operator bundle image arm64
  variables:
    IMAGE_SUFFIX: '-release-openshift-arm64'
    LOCK_FILE: stackgres-operator-release-openshift-bundle-build-image
    IMAGE_MODULE_NAME: operator-release-openshift-bundle-image

.release operator bundle image multi archs:
  extends: .release image multi archs
  tags:
    - stackgres-runner-v2
  variables:
    IMAGE_SUFFIX: '-release'
    IMAGE_BASE_NAME: stackgres/operator-bundle
  only:
    variables:
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_DEPLOY != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_RELEASE_IMAGE

release operator bundle image multi archs:
  extends: .release operator bundle image multi archs

release operator openshift bundle image multi archs:
  extends: .release operator bundle image multi archs
  variables:
    IMAGE_SUFFIX: '-release-openshift'
