
.build image:
  image: $CI_REGISTRY/$SG_CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: image build
  timeout: 1 hour
  script:
    - |
      [ "$DEBUG" != true ] || set -x
      export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}$IMAGE_SUFFIX"
      export IMAGE_NAME="$CI_REGISTRY/$SG_CI_PROJECT_PATH/$IMAGE_BASE_NAME:$IMAGE_TAG"
      mkdir -p $HOME/.docker                                                                                                                                                                               
      cat "$DOCKER_AUTH_CONFIG" > "$HOME/.docker/config.json"                                                                                                                                              
      echo | docker login "$CI_REGISTRY" || \
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      flock "$LOCK_FILE" \
        sh stackgres-k8s/ci/build/build-gitlab.sh build \
          "$IMAGE_MODULE_NAME"
      HASH_IMAGE_NAME="$(sh stackgres-k8s/ci/build/build-functions.sh image_name "$IMAGE_MODULE_NAME")"
      docker pull "$HASH_IMAGE_NAME"
      docker tag "$HASH_IMAGE_NAME" "$IMAGE_NAME"
      docker push "$IMAGE_NAME"
  retry: 2

.build image multi archs:
  image: docker:24.0.7
  stage: image build multi archs
  timeout: 1 hour
  script:
    - |
      [ "$DEBUG" != true ] || set -x
      export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}$IMAGE_SUFFIX"
      export IMAGE_NAME="$IMAGE_BASE_NAME:$IMAGE_TAG"
      export TARGET_IMAGE_NAME="$CI_REGISTRY/$SG_CI_PROJECT_PATH/$IMAGE_NAME"
      mkdir -p $HOME/.docker                                                                                                                                                                               
      cat "$DOCKER_AUTH_CONFIG" > "$HOME/.docker/config.json"                                                                                                                                              
      echo | docker login "$CI_REGISTRY" || \
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      cd stackgres-k8s/src
      ARCH_LIST="amd64 $(
        if [ "$DO_ARM" = true ] \
          || { [ "$SKIP_ARM" != true ] && [ -n "$CI_COMMIT_TAG" ]; }
        then
          echo arm64
        fi
        )"
      if docker manifest inspect "$TARGET_IMAGE_NAME" >/dev/null 2>&1
      then
        docker pull registry.gitlab.com/ongresinc/stackgres/placeholder
        docker tag registry.gitlab.com/ongresinc/stackgres/placeholder "$TARGET_IMAGE_NAME"
        docker push "$TARGET_IMAGE_NAME"
      fi
      docker manifest rm "$TARGET_IMAGE_NAME" 2>/dev/null || true
      docker manifest create "$TARGET_IMAGE_NAME" $(
        for ARCH in $ARCH_LIST
        do
          echo "$TARGET_IMAGE_NAME-$ARCH "
        done)
      docker manifest push "$TARGET_IMAGE_NAME"
  retry: 2

.build jvm image amd64:
  extends: .build image
  dependencies:
    - build amd64
  tags:
    - stackgres-runner-v2
    - linux-amd64
  variables:
    IMAGE_SUFFIX: '-jvm-amd64'

.build native image amd64:
  extends: .build image
  dependencies:
    - build amd64
  tags:
    - stackgres-runner-v2
    - linux-amd64
  variables:
    IMAGE_SUFFIX: '-amd64'
  only:
    variables:
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_NATIVE != "true"  && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_NATIVE

build operator jvm image amd64:
  extends: .build jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/operator
    LOCK_FILE: stackgres-operator-build-jvm-image
    IMAGE_MODULE_NAME: operator-jvm-image

build restapi jvm image amd64:
  extends: .build jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/restapi
    LOCK_FILE: stackgres-restapi-build-jvm-image
    IMAGE_MODULE_NAME: restapi-jvm-image

build jobs jvm image amd64:
  extends: .build jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/jobs
    LOCK_FILE: stackgres-jobs-build-jvm-image
    IMAGE_MODULE_NAME: jobs-jvm-image

build cluster-controller jvm image amd64:
  extends: .build jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller
    LOCK_FILE: stackgres-cluster-controller-build-jvm-image
    IMAGE_MODULE_NAME: cluster-controller-jvm-image

build stream jvm image amd64:
  extends: .build jvm image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/stream
    LOCK_FILE: stackgres-stream-build-jvm-image
    IMAGE_MODULE_NAME: stream-jvm-image

build operator native image amd64:
  extends: .build native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/operator
    LOCK_FILE: stackgres-operator-build-native-image
    IMAGE_MODULE_NAME: operator-native-image

build restapi native image amd64:
  extends: .build native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/restapi
    LOCK_FILE: stackgres-restapi-build-native-image
    IMAGE_MODULE_NAME: restapi-native-image

build jobs native image amd64:
  extends: .build native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/jobs
    LOCK_FILE: stackgres-jobs-build-native-image
    IMAGE_MODULE_NAME: jobs-native-image

build cluster-controller native image amd64:
  extends: .build native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller
    LOCK_FILE: stackgres-cluster-controller-build-native-image
    IMAGE_MODULE_NAME: cluster-controller-native-image

.build stream native image amd64:
  extends: .build native image amd64
  variables:
    IMAGE_BASE_NAME: stackgres/stream
    LOCK_FILE: stackgres-stream-build-native-image
    IMAGE_MODULE_NAME: stream-native-image

build admin-ui image amd64:
  extends: .build image
  dependencies:
    - build amd64
  tags:
    - stackgres-runner-v2
    - linux-amd64
  variables:
    IMAGE_SUFFIX: '-amd64'
    IMAGE_BASE_NAME: stackgres/admin-ui
    LOCK_FILE: stackgres-adminui-build-image
    IMAGE_MODULE_NAME: admin-ui-image

.build jvm image arm64:
  extends: .build image
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - linux-arm64
  variables:
    IMAGE_SUFFIX: '-jvm-arm64'
  only:
    variables:
      - $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_ARM

.build native image arm64:
  extends: .build image
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - linux-arm64
  variables:
    IMAGE_SUFFIX: '-arm64'
  only:
    variables:
      - $SKIP_NATIVE != "true" && $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_NATIVE && $DO_ARM

build operator jvm image arm64:
  extends: .build jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/operator
    LOCK_FILE: stackgres-operator-build-jvm-image
    IMAGE_MODULE_NAME: operator-jvm-image

build restapi jvm image arm64:
  extends: .build jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/restapi
    LOCK_FILE: stackgres-restapi-build-jvm-image
    IMAGE_MODULE_NAME: restapi-jvm-image

build jobs jvm image arm64:
  extends: .build jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/jobs
    LOCK_FILE: stackgres-jobs-build-jvm-image
    IMAGE_MODULE_NAME: jobs-jvm-image

build cluster-controller jvm image arm64:
  extends: .build jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller
    LOCK_FILE: stackgres-cluster-controller-build-jvm-image
    IMAGE_MODULE_NAME: cluster-controller-jvm-image

build stream jvm image arm64:
  extends: .build jvm image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/stream
    LOCK_FILE: stackgres-stream-build-jvm-image
    IMAGE_MODULE_NAME: stream-jvm-image

build operator native image arm64:
  extends: .build native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/operator
    LOCK_FILE: stackgres-operator-build-native-image
    IMAGE_MODULE_NAME: operator-native-image

build restapi native image arm64:
  extends: .build native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/restapi
    LOCK_FILE: stackgres-restapi-build-native-image
    IMAGE_MODULE_NAME: restapi-native-image

build jobs native image arm64:
  extends: .build native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/jobs
    LOCK_FILE: stackgres-jobs-build-native-image
    IMAGE_MODULE_NAME: jobs-native-image

build cluster-controller native image arm64:
  extends: .build native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller
    LOCK_FILE: stackgres-cluster-controller-build-native-image
    IMAGE_MODULE_NAME: cluster-controller-native-image

.build stream native image arm64:
  extends: .build native image arm64
  variables:
    IMAGE_BASE_NAME: stackgres/stream
    LOCK_FILE: stackgres-stream-build-native-image
    IMAGE_MODULE_NAME: stream-native-image

build admin-ui image arm64:
  extends: .build image
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - linux-arm64
  variables:
    IMAGE_SUFFIX: '-arm64'
    IMAGE_BASE_NAME: stackgres/admin-ui
    LOCK_FILE: stackgres-adminui-build-image
    IMAGE_MODULE_NAME: admin-ui-image
  only:
    variables:
      - $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_ARM

.build jvm image multi archs:
  extends: .build image multi archs
  tags:
    - stackgres-runner-v2
  variables:
    IMAGE_SUFFIX: '-jvm'

.build native image multi archs:
  extends: .build image multi archs
  tags:
    - stackgres-runner-v2
  variables:
    IMAGE_SUFFIX: ''
  only:
    variables:
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_NATIVE

build operator jvm image multi archs:
  extends: .build jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/operator

build restapi jvm image multi archs:
  extends: .build jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/restapi

build jobs jvm image multi archs:
  extends: .build jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/jobs

build cluster-controller jvm image multi archs:
  extends: .build jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller

build stream jvm image multi archs:
  extends: .build jvm image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/stream

build operator native image multi archs:
  extends: .build native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/operator

build restapi native image multi archs:
  extends: .build native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/restapi

build jobs native image multi archs:
  extends: .build native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/jobs

build cluster-controller native image multi archs:
  extends: .build native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/cluster-controller

.build stream native image multi archs:
  extends: .build native image multi archs
  variables:
    IMAGE_BASE_NAME: stackgres/stream

build admin-ui image multi archs:
  extends: .build image multi archs
  tags:
    - stackgres-runner-v2
  variables:
    IMAGE_SUFFIX: ''
    IMAGE_BASE_NAME: stackgres/admin-ui

.build operator bundle image amd64:
  extends: .build image
  dependencies:
    - build amd64
  tags:
    - stackgres-runner-v2
    - linux-amd64
  variables:
    IMAGE_SUFFIX: '-amd64'
    IMAGE_BASE_NAME: stackgres/operator-bundle

.build operator bundle image arm64:
  extends: .build image
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - linux-arm64
  variables:
    IMAGE_SUFFIX: '-arm64'
    IMAGE_BASE_NAME: stackgres/operator-bundle
  only:
    variables:
      - $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_ARM

build operator bundle image amd64:
  extends: .build operator bundle image amd64
  variables:
    LOCK_FILE: stackgres-operator-bundle-build-image
    IMAGE_MODULE_NAME: operator-bundle-image

build operator bundle image arm64:
  extends: .build operator bundle image arm64
  variables:
    LOCK_FILE: stackgres-operator-bundle-build-image
    IMAGE_MODULE_NAME: operator-bundle-image

build operator openshift bundle image amd64:
  extends: .build operator bundle image amd64
  variables:
    IMAGE_SUFFIX: '-openshift-amd64'
    LOCK_FILE: stackgres-operator-openshift-bundle-build-image
    IMAGE_MODULE_NAME: operator-openshift-bundle-image

build operator openshift bundle image arm64:
  extends: .build operator bundle image arm64
  variables:
    IMAGE_SUFFIX: '-openshift-arm64'
    LOCK_FILE: stackgres-operator-openshift-bundle-build-image
    IMAGE_MODULE_NAME: operator-openshift-bundle-image

.build operator bundle image multi archs:
  extends: .build image multi archs
  tags:
    - stackgres-runner-v2
  variables:
    IMAGE_BASE_NAME: stackgres/operator-bundle

build operator bundle image multi archs:
  extends: .build operator bundle image multi archs

build operator openshift bundle image multi archs:
  extends: .build operator bundle image multi archs
  variables:
    IMAGE_SUFFIX: '-openshift'

.build pglambda javascript image amd64:
  extends: .build image
  tags:
    - stackgres-runner-v2
    - linux-amd64
  variables:
    IMAGE_SUFFIX: '-javascript-amd64'
    IMAGE_BASE_NAME: stackgres/pglambda

.build pglambda javascript image arm64:
  extends: .build image
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - linux-arm64
  variables:
    IMAGE_SUFFIX: '-javascript-arm64'
    IMAGE_BASE_NAME: stackgres/pglambda
  only:
    variables:
      - $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_ARM

build pglambda javascript image amd64:
  extends: .build pglambda javascript image amd64
  variables:
    LOCK_FILE: stackgres-pglambda-javascript-build-image
    IMAGE_MODULE_NAME: pglambda-javascript-image

build pglambda javascript image arm64:
  extends: .build pglambda javascript image arm64
  variables:
    LOCK_FILE: stackgres-pglambda-javascript-build-image
    IMAGE_MODULE_NAME: pglambda-javascript-image

.build pglambda javascript image multi archs:
  extends: .build image multi archs
  tags:
    - stackgres-runner-v2
  variables:
    IMAGE_BASE_NAME: stackgres/pglambda

build pglambda javascript image multi archs:
  extends: .build pglambda javascript image multi archs
  variables:
    IMAGE_SUFFIX: '-javascript'
