
.build native executable:
  image: $CI_REGISTRY/$SG_CI_PROJECT_PATH/$SG_CI_IMAGE_NAME
  stage: build 2
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: ""
    MAVEN_EXTRA_ARGS: ""
    QUARKUS_NATIVE_NATIVE_IMAGE_XMX: 18g
  timeout: 1 hour
  script:
    - |
      sh stackgres-k8s/ci/build/build-gitlab.sh build \
        "$MODULE"
  retry:
    max: 2
    when: [ unknown_failure, api_failure, stuck_or_timeout_failure, runner_system_failure, runner_unsupported,
     stale_schedule, job_execution_timeout, archived_failure, unmet_prerequisites, scheduler_failure, data_integrity_failure ] 
  cache:
    - key:
        files:
          - stackgres-k8s/src/pom.xml
      paths:
      - .m2/
      when: always
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/src/*/target/stackgres-*-runner
      - stackgres-k8s/src/*/target/lib/
      - stackgres-k8s/src/*/target/stackgres-*-runner.jar

.build native executable amd64:
  extends: .build native executable
  dependencies:
    - build amd64
  tags:
    - stackgres-runner-v2
    - stackgres-native-build-runner
    - linux-amd64
  only:
    variables:
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME == "current"
      - $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_NATIVE

build operator native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-operator"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,operator"
    MODULE: "operator-native"

build restapi native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-restapi"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,restapi"
    MODULE: "restapi-native"

build jobs native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-jobs"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,jobs"
    MODULE: "jobs-native"

build cluster-controller native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-cluster-controller"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,cluster-controller"
    MODULE: "cluster-controller-native"

.build stream native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-stream"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,stream"
    MODULE: "stream-native"

.build native executable arm64:
  extends: .build native executable
  dependencies:
    - build arm64
  tags:
    - stackgres-runner-v2
    - stackgres-native-build-runner
    - linux-arm64
  only:
    variables:
      - $SKIP_NATIVE != "true" && $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_NATIVE && $DO_ARM

build operator native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-operator"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,operator"
    MODULE: "operator-native"

build restapi native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-restapi"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,restapi"
    MODULE: "restapi-native"

build jobs native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-jobs"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,jobs"
    MODULE: "jobs-native"

build cluster-controller native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-cluster-controller"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,cluster-controller"
    MODULE: "cluster-controller-native"

.build stream native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-stream"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,stream"
    MODULE: "stream-native"
